source/include/FluidMaxWrapper.hpp
* resolves #2
* see also flucoma/flucoma-core#12
* Adds inlet / outlet information for all objects: RT objects need their own individual strings & buf* objects / model objects have uniform labelling across objects 
* This also de-noises modelling objects by removing useless signal inlet and threading attributes / process() selectors
=> Add inlet / outlet assistance

help/fluid.plotter.maxhelp
This takes on the advice given by @weefuzzy to improve the help file. Thanks Owen <3
=> update plotter help file

help/fluid.waveform~.maxhelp, init/fluid.waveform-init.txt, jsui/fav-max.js, jsui/fluid.waveform~.js
This includes fluid.waveform directly into the repository and package for distribution.
In the future this will be part of the build process, but for now the versions are moving slowly for fluid.waveform~ and it is safe to manually include it.﻿
=> add fluid.waveform~ to the main repo

README.md
=> crediting the new team

extras/Fluid Corpus Manipulation Toolkit.maxpat
This makes 4 changes:
1. Add `fluid.grid~` to unsupervised machine learning
2. Move `fluid.bufstft~` to buffer in/out audio analysis
3. Buffer analysis category has become "statistical analysis"
4. `fluid.stats~` added to statistical analysis
=> Update Extras Overview

init/fluid-jsui-init.txt, init/fluid.waveform-init.txt
This will show the plotter and waveform in the autocomplete objectlist when typing a new object. Just a small contribution, but hopefully useful :).
=> adds to objectlist

help/fluid.transients~.maxhelp
Mostly a cosmetic upgrade and simplifying some of the user interface.
=> Transients Help File

help/fluid.demosound.maxpat, help/fluid.sines~.maxhelp
This updates the fluid.sines~ help file.
First tab is mostly cosmetic upgrades while the second requires a little more overhaul on the user interface.﻿
=> Sines Help File

jsui/fluid.plotter.js
Fixes the assistance on fluid.plotter~.
=> fix plotter outlets

help/fluid.bufselect~.maxhelp, help/fluid.learn.maxpat
Adds a small update to the BufSelect help file.﻿
=> [Review Changes] BufSelect Help File

help/fluid.chroma~.maxhelp, help/fluid.learn.maxpat
Updates to the fluid.chroma~ help file.
=> [Review Changes] Chroma Help File

.github/workflows/nightly.yaml
Refactors the continuous integration out for maximal reuse of code through composite actions.
=> [CI] Refactor and use composite actions

.github/workflows/nightly.yaml
Try to make CI to produce fat binaries for macOS and ARM.
=> [CI] Fat Binaries

.github/workflows/nightly.yaml
Solves the issue of docs pulling main instead of dev.﻿
=> [CI] Fix Documentation Build

help/fluid.sines~.maxhelp
A few cosmetic upgrades to make the visual aesthetic normalised with our own style as well a the broader max conventions of docs.﻿
=> [Docs] Sines Help File

help/fluid.bufchroma~.maxhelp
Fixes layout issues described in:
https://github.com/flucoma/flucoma-max/issues/111
=> [Docs] Fix Layout issues in BufChroma help

help/fluid.dataset~.maxhelp
Added a "frombuffer" tab and normalised some of the styling to be more consistent with Max and our own documentation.
=> [Docs] Dataset Help file

help/fluid.bufchroma~.maxhelp, help/fluid.bufnndsvd~.maxhelp, help/fluid.bufselect~.maxhelp, help/fluid.bufstft~.maxhelp
- add back blocking attribute
- add attribute blocking to bufnndsvd
- add tab to bufstft
- add tab to bufselect
=> [Docs] Blocking Help Tab

help/fluid.loudness~.maxhelp
Updates the loudness help file.﻿
=> [Docs] Loudness Help File

help/fluid.ampslice~.maxhelp, help/fluid.flucomaorg.maxpat, help/fluid.learn.maxpat
This cleans up and reorders the structure of the AmpSlice help file.
It now starts with a very simple musical example and then attempts to explain the many parameters of the object under the hood.
=> AmpSlice Help File

help/fluid.bufaudiotransport~.maxhelp
This prepares the audiotransport documentation for the pending changes to the AudioTransport interface.﻿
=> [Fix] Change source names for pending audiotransport changes

help/fluid.bufaudiotransport~.maxhelp
Updates bufaudiotransport.
Mind taking a look @tremblap?﻿
=> [Docs] BufAudioTransport Help File

help/fluid.normalize~.maxhelp
Updates the normalize help file.
@tremblap do you mind taking a look at this?
=> [Docs] Normalize Help File

help/fluid.datasetquery~.maxhelp
Updates the fluid.datasetquery~ help file.
I went with the approach of separating out the ideas as much as possible as it was all stacked on top of each other in the original verison. @tremblap would you be able to have a glance and tell me what you think?
=> [Docs] DataSetQuery Help File

jsui/fluid.plotter.js
The RGB function that converts from hex was never working, and now does.﻿
=> [Fix] fluid.plotter~ RGB parsing function

source/include/FluidMaxWrapper.hpp
=> fixes #148 – crash on empty dump under some conditions

help/fluid.bufonsetslice~.maxhelp, help/fluid.onsetslice~.maxhelp
- update onsetslice (rt) help file
- start work unpeeling bufonsetslice
=> [Docs] BufOnsetSlice Help File

help/fluid.bufsines~.maxhelp
This is mostly a buffer translation of the sines help file.﻿
=> [Docs] BufSines Help File

help/fluid.kdtree~.maxhelp, help/fluid.umap~.maxhelp
This solves issue #181 It can be tested with the current tip of dev on Core, or for more excitement, with PR #135 on core
=> kdtreehelp: now loads programatically, in order, from the stored labelset

source/include/FluidMaxWrapper.hpp
see https://github.com/orgs/flucoma/teams/flucoma-dev/discussions/3
=> optional args: add to wrapper

help/fluid.bufonsetslice~.maxhelp, help/fluid.onsetslice~.maxhelp
In ab4c700657827f813d670d1999b406e354091451 I accidentely overwrote the preceding PR of changes. This restores those changes.
- restore to previous state
- fix some style errors
- fix style issues
=> [Fix] Missing OnsetSlice Files

help/fluid.bufthresh~.maxhelp
Translates the SC BufThresh help file﻿
=> [Help] BufThresh Translation of SuperCollider

help/fluid.bufpitch.grain.maxpat, help/fluid.bufpitch~.maxhelp, help/fluid.pitch~.maxhelp
- layout
- cleanup and translate
- update bufpitch to match sc
=> [Help] Pitch and BufPitch SC Translations

help/fluid.bufampslice~.maxhelp, help/fluid.bufcompose~.maxhelp, help/fluid.bufnoveltyslice~.maxhelp, help/fluid.bufonsetslice~.maxhelp
- fix bufcompose
- fix bufampslice playback
- change from groove to play
=> [Fix] Various Bug Fixes From PA

help/fluid.buf2list.maxhelp
As it says on the tin, enhances the help file for fluid.buf2list a little and gives an example use case.
=> [Docs] Enhanced fluid.buf2list help file

help/fluid.bufmelbands~.maxhelp, help/fluid.melbands~.maxhelp
=> [Docs] MelBands + BufMelBands Translation

help/fluid.list2buf.maxhelp, source/include/clients/nrt/FluidListToBuf.hpp
Updates fluid.list2buf help file﻿
=> [Docs] Update fluid.list2buf

help/fluid.nmffilter~.maxhelp
=> [Docs] NMFFilter Translation

help/fluid.mlpclassifier~.maxhelp
Translation of Ted's work on the SC help files.
This help file will have a strong link to the videos and a bigger example patch to demonstrate the canonical musical application of audio classification. Having this live outside the help file reduces the bloat and "ARGHHHHH" feeling of opening it up.
These connections don't yet exist because these examples don't but there will be an accompanying issue.
=> [Docs] MLPClassifier Translation

help/fluid.mds~.maxhelp
=> [Docs] MDS SC Translation

help/fluid.chroma~.maxhelp, help/fluid.melbands~.maxhelp, help/fluid.mfcc~.maxhelp, help/fluid.nmfmatch~.maxhelp, help/fluid.stats.maxhelp
Replaces all instances of @size with @history.
=> [Fix] @size to @history for fluid.stats

extras/Fluid Corpus Manipulation Toolkit.maxpat, help/fluid.bufampfeature~.maxhelp, help/fluid.bufnoveltyfeature~.maxhelp, help/fluid.bufonsetfeature~.maxhelp, help/fluid.bufselect~.maxhelp, help/fluid.bufstats~.maxhelp, help/fluid.kmeans~.maxhelp
Fixes various bugs that have been accumulated in help files due to interface changes.
Addresses:
https://github.com/flucoma/flucoma-max/issues/191
https://github.com/flucoma/flucoma-max/issues/236
https://github.com/flucoma/flucoma-max/issues/212
https://github.com/flucoma/flucoma-max/issues/178
=> [Fix] Various patcher bugs

extras/Fluid Corpus Manipulation Toolkit.maxpat, help/fluid.bufnmfseed~.maxhelp
See https://github.com/flucoma/flucoma-core/pull/173
=> BufNNDSVD -> BufNMFSeed

help/fluid.buftransientslice~.maxhelp, help/fluid.buftransients~.maxhelp, help/fluid.transientslice~.maxhelp, help/fluid.transients~.maxhelp
- translate transientslice
- translate buftransientslice
- fluid.transients~ translation
- cosmetic
- translate buftransients
=> [Docs] Transients Family Translation 

help/fluid.ampgate~.maxhelp, help/fluid.bufampgate~.maxhelp
- grid help file
- translate ampgate
=> [Docs] AmpGate SC Translation

help/fluid.kmeans~.maxhelp, help/fluid.skmeans~.maxhelp, patchers/fluid.dataloader.maxpat
Adds a distances tab for retrieving and using distances from the (s)kmeans object(s).
=> [Docs] (S)Kmeans Distances Tab

help/fluid.grid~.maxhelp, help/fluid.kdtree~.maxhelp, help/fluid.mds~.maxhelp, help/fluid.mlpclassifier~.maxhelp, help/fluid.umap~.maxhelp
Adds @border 0 to every plotter instance for _aesthetics_
=> [fix] All instances of plotter with @border 0 

source/include/FluidMaxWrapper.hpp
fixes #193 
* better inlet info for buffer processors
* fluid.stats had an extra inlet 😬 
* hot and cold colouring added where needed 
* NMFMorph is deeply problematic, really needs a refactor before we can cope with its weirdness
=> Wrapper: Improve inlet assists and rogue inlet on fluid.stats

help/fluid.kdtree~.maxhelp
=> fix the 404 link in kdtree example code

patchers/fluid_decomposition.blocking.maxpat
Fixes issue linked in https://github.com/flucoma/flucoma-max/issues/335.
=> fixes blocking tab typo

source/include/FluidMaxWrapper.hpp
Implements byzantine rules for handling the derivation of runtime param maxes by argument, attribute etc.
=> Wrapper: constrain param maxima

.github/workflows/nightly.yml, .github/workflows/release.yml
CI changes: nightlies from `main`, releases from `production`
=> Make `main` great again 

package-info.json.in
This version now includes 10.9.x as the minimum macOS version
=> edits for package-info.json in PM-expected format

help/fluid.pitch~.maxhelp
=> GUI fix in fluid.pitch second tab

examples/tutorials/classification.maxpat, examples/tutorials/corpus-explorer.maxpat, examples/tutorials/regression.maxpat
Organised the three max tutorials and added instructions on how to use them. Also fixed an issue with zlmaxsize in the corpus explorer
=> Max tutorial corrections

help/fluid.umap~.maxhelp
Fixed #310 - fluid.umap~ tab 1 saying wrong number of dimensions. Also corrected the step numbers on tab 2 that were missing a step2.
=> Fixed #310 - typo in number of dimensions in fluid.umap~

source/include/FluidMaxWrapper.hpp
=> Match pd wrapper

help/fluid.datasetquery~.maxhelp
see related PRs in all repos (core, docs, sc, max, pd)
=> removes the word rows from the interface of dsquery.limit

.github/workflows/nightly.yml, .github/workflows/release.yml, CMakeLists.txt, QuickStart.md, help/fluid.jit.plotter.maxhelp, local_docs/fluid.audiofilesin.maxref.xml, local_docs/fluid.buf2list.maxref.xml, local_docs/fluid.concataudiofiles.maxref.xml, local_docs/fluid.jit.plotter.maxref.xml, local_docs/fluid.list2buf.maxref.xml, local_docs/fluid.plotter.maxref.xml, local_docs/fluid.waveform~.maxref.xml, package-info.json.in, vignettes/flucoma/automatic_buffer_and_dataset_management.maxvig.xml, vignettes/flucoma/bufcompose_macros.maxvig.xml
paired with https://github.com/flucoma/flucoma-docs/pull/206
=> harmonise package references to FluidCorpusManipulation

help/fluid.dataset~.maxhelp, help/fluid.kdtree~.maxhelp, help/fluid.labelset~.maxhelp, help/fluid.mlpclassifier~.maxhelp, help/fluid.umap~.maxhelp, patchers/fluid.dsinterface.maxpat
fix the new execution priority in max helps and patchers for read and write.
=> fix deferlow behaviour of read in examples and helps

package-info.json.in
added an `extends` field as per #442
Per @weefuzzy 's suggestion
=> added "extends" to package-info.json

help/fluid.dataset~.maxhelp
this is linked to https://github.com/flucoma/flucoma-core/pull/305
=> dataset:tobuffer: adds a flag to flip the ID-label
