source/script/max-posttarget.cmake
source/script/max-pretarget.cmake

**commonsyms is no longer included in the `.framework` (which was apparently an error), so needs to be built with the mxo on Mac as well as windows now** 
This seems to work fine against the v7 SDK. Weirdly it wouldn't work until the flag for including the precompiled headers was moved from the CXXFLAGs into the target compiler options (which is better anyway). Unfortunately, the error you get when this is broken is not at all helpful (it dies trying to find an old carbon header, Files.h)
**The directory structure has changed such that what used to be `sources/c74support` can now be `sources\/max-sdk-base/c74support`.**
This gives three possible scenarios:
1. Legacy SDK, with includes where they used to be 
2. New complete SDK, with sources folder, and addition `max-sdk-base` path 
3. …

Adjust cmake to handle changes to Max SDK from 8.2 onwards

---

source/include/FluidMaxWrapper.hpp

fixes #60 by adding missing `return` to exit on error

Add return to load() when missing arguments

---

jsui/fluid.plotter.js

This adds several changes to the fluid.plotter object. Fundamentally it changes how the data of the fluid.dataset~ dump is dealt with.
1) No longer are the points in the plot an `array`. They are now a `JSON Object`. This has the consequence of each point being a key-value pair with information about its position, size and colour. This means that points are now unique. This has consequences on the `addpoint` message below.
2) `addpoint` now has mirrored functionality with `fluid.datasets~` method. If the point already exists, and you try to use the advanced interface to manually add a point with the same identifier it will throw an error.
3) To make the changes for `addpoint` feel like one is losing something, `setpoint` now exists for changing the properties of individual points after …

reconfigure fluid.plotter interface

---

CMakeLists.txt

This makes `cmake` copy the `misc` folder into the distribution package when using the install target.﻿

Copy misc folder on install target

---

jsui/fluid.plotter.js

Prior to this PR fluid.plotter would not reset the points in its internal JSON object when receiving a new dictionary in the left inlet.
This meant that changing the size to a smaller set of points would leave the old points in the object between giving it new data (if the keys were not overwritten).
This PR explicitly resets the points if all the preliminary checks on the integrity of the dictionary pass.﻿

fluid.plotter reset points on receiving setdict()

---

source/include/FluidMaxWrapper.hpp

closes #20 
In principle consistent with other Max objects (which aren't wholly consistent in edge cases). I've tried to do what `[dict]` does
* Absolute paths should pass through unchanged 
* A path-less file name passed to `write` in a *saved* patch will use the same folder as the patch 
* A path-less file name passed to `write` in a *unsaved* patch will use the same folder from which the last patch was opened 
* If there was no last-opened-patch (e..g unsaved patch after Max has just started, no re-opened windows), like `dict` (and `jit.matrix`) files end up in `/Applications` (!!) [this isn't me, this is what the Max API returns as a candidate path 🤷‍♂️ ] 
Needs verifying on Max 7 and Windows

Add relative path file writing for data objects

---

help/fluid.kdtree~.maxhelp

This updates the fluid.kdtree~ help file to use the fluid.plotter abstraction.
Content-wise it has not been changed, rather, it has just been kept in line with the other help files that will incrementally make use of the plotter rather than ad-hoc abstractions.

KDTree Help File

---

.github/workflows/nightly.yaml

When github actions create a pre-release nightly there has to be a tag associated to that release. I was using one called 1.0.0-nightly, but I think nightlies are inherently versionless and their version information is compiled into the obecjts anyway. The actions will also delete and move the tag as necessary so the name of it is just another thing to manage if it contains specific major version information. Thus it is now just `nightly`.﻿

CI tag name

---

CMakeLists.txt

Previously when running something like `ninja install` the package folder in `release-packaging` would contain spaces. This removes those spaces.﻿

Remove spaces from installation path name

---

.github/workflows/nightly.yaml

Triggers a custom version of the nightly build CI action on PRs. This gives an inline report of whether the build worked for each PR.

Trigger compilation from CI on PRs

---

help/fluid.chroma~.maxhelp
help/fluid.learn.maxpat

The fluid.learn abstraction is going to be common to all of the object help files.
This fixes its layout which was snapping to the parent patcher grid when the offset was not aligned with that grid.

Fix fluid.learn abstraction not displaying properly

---

misc/fluid.bufloader.maxpat

This adds a new abstraction that can be used in a bpatcher for helping users load sounds from the media folder into buffers.
It also constructs an internal lookup table so you can set a default, ala @file filename.wav.

Load media files from package abstraction

---

help/fluid.waveform~.maxhelp
jsui/fav-max.js
jsui/fluid.waveform~.js

Updates fluid.waveform~ to have parity with the SuperCollider waveform.
`addlayer line` is now `addlayer featurebuf`.
`addlayer image` is now `addlayer imagebuf`
`addlayer wave` is now `addlayer audiobuf`
All calls are backwards compatible too.

[Enhance] Update fluid.waveform~

---

help/fluid.bufchroma~.maxhelp

The current patch has adapts to the maxnumchroma, rather than the numchroma. This PR changes it so that the sonification patch for the chroma respects the numchroma.﻿

[Fix] BufChroma sonification adapts to numchroma

---

source/include/MaxBufferAdaptor.hpp

Address Sanitizer found out that when our objects are destroyed we weren't being completely safe with buffer references

Max buffer references weren't being freed safely (ASan)

---

jsui/fluid.plotter.js

Individual point colours now take precedence of a labelset~ colour system to avoid individual points absorbing the last cluster's `color`.

[Fix] Plotter Colours

---

help/fluid.plotter.maxhelp
jsui/fluid.plotter.js

Adds the ability to drag a square of an area of the plotter to zoom in.
The shortcut is option + drag for Mac and whatever that translates to on Windows (winkey?)
You can reset the xrange/yrange to whatever was stored via message previously with control + click.
Example can be seen on the final tab of the help file if you want to play with it easily.

[Feature] Plotter drag to zoom

---

source/include/FluidMaxWrapper.hpp

See https://github.com/flucoma/flucoma-core/pull/108

MaxWrapper: Add choices param (list of symbols <-> bitset)

---

help/fluid.bufstats~.maxhelp
help/fluid.datasetquery~.maxhelp
help/fluid.dataset~.maxhelp
help/fluid.grid~.maxhelp
help/fluid.kdtree~.maxhelp
help/fluid.kmeans~.maxhelp
help/fluid.labelset~.maxhelp
help/fluid.normalize~.maxhelp
help/fluid.plotter.maxhelp
help/fluid.umap~.maxhelp

Many patches were broken due to the new changes in fluid.dataset~.
I've fixed those (mostly changed connections) and taken the liberty to "Maxify" the style of many of the patchers.
- update dataset
- fix broken cabling in datasetquery
- update kmeans
- make more max-like in style
- "maxify" the style
- fix connections and maxify style of labelset~
- fix connections in umap and maxify
- fix connections and mafixy fluid.grid~
- update kdtree~ help with fixed cables and max style
- fix connections and maxify style of normalize
- cosmetic upgrades

[Fix] Broken patches due to new dataset/buffer interface interface

---

help/fluid.ampslice~.maxhelp
help/fluid.bufnoveltyslice~.maxhelp
help/fluid.bufonsetslice~.maxhelp
help/fluid.noveltyslice~.maxhelp
help/fluid.onsetslice~.maxhelp

Adds bigger maxsizes for things that it can be applied to so that those parameters are modulatable in help files. Assuredly this is not the end of these changes but this captures the evident low hanging fruit.

[Fix] Saner maximum sizes for modulatable examples

---

help/fluid.plotter.maxhelp
init/fluid-jsui-init.txt
jsui/fluid.plotter.js

Refactors various internal components such that state is only ever touched in one place at a time.
Use `const` where data should be immutable.
Change the precedence of colour assignments. This changes the behaviour (rather fixes it because it never worked):
1. Set a dictionary from `fluid.kmeans~` for example those clusters get those colours
2. Change some of the points with a custom colouring using `pointcolor`
3. Apply a new dictionary from another `fluid.kmeans~`
The final stage will overwrite the custom colours now.
Also fixes the help file.

[Fix] Plotter internal state management

---

help/fluid.bufcompose~.maxhelp
help/fluid.bufthreaddemo~.maxhelp
help/fluid.noveltyfeature~.maxhelp
help/fluid.onsetfeature~.maxhelp

Searches for an eliminates any `ezdac~` that don't have their local flags switched on.

[Fix] Non-local ezdac~

---

CMakeLists.txt

fixes #296 : make sure `flucoma-obj-qlookup.json` and `max.db.json` are `install`ed

CMake: Install Max index json files for object lookup

---

extras/Fluid Corpus Manipulation Toolkit.maxpat

- The visual order of the entries in the inspiration tab do not correspond with where their links (learn/YouTube) send to, e.g. Alice & Chris's learn / YouTube link is on Lauren's page etc. as you go down the list. 
- Some YouTube videos are attached to the wrong performers too. 
- I kept the order found in the original Presentation-mode patcher and corrected:
- `lines 1603-1635`: The order of the performer names in `[coll fluid-composer-learns]`
- `lines 1685-1717`: The URLs to the incorrectly linked YouTube videos in `[coll fluid-composer-links]`

Corrected the URLs to learn/YouTube content in Inspiration tab of the Toolkit patch

---

.github/workflows/nightly.yml
.github/workflows/release.yml

As the title explains this bumps the artifact version, which mitigates a deprecation of node 12.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Bump Download Artifact Action Version

---

source/include/clients/nrt/FluidListToBuf.hpp

@AlexHarker 
As discussed in https://github.com/flucoma/flucoma-max/pull/372, here's a new PR with a cleaned up branch.
This fixes the original static cast bug that arose from a CLASS_ATTR_SYM being used for a t_atom type.
Instead of changing the CLASS_ATTR, as the variable is only ever used as a t_atom once and is being converted to a symbol type many times, it is changed to a t_symbol type and now only ever converted to a t_atom once (lines 257-259).

Fixes issue #371 - outName static cast error in debug builds

---

help/fluid.labelset~.maxhelp

Added a missing `print` object to the fluid.labelset~ help file as per issue #332 as well as correcting a typo on tab4.

Fixed #332 - issue with fluid.labelset~ help file

---

help/fluid.bufcompose~.maxhelp

Fixed #273  bufcompose~ having confusing buttons by changing them to a `live.tab`. This makes each toggle stay active whilst it's corresponding sound is playing.

Fixed #273 - bufcompose~ has confusing buttons

---

source/include/FluidMaxWrapper.hpp

The assert was incorrect - shouldn't have pushed without testing/thinking. This *should* now be correct.

Correct assert

---

source/include/FluidMaxWrapper.hpp

Fixes the bug in the nightlies with objects instacrashing.

Don't attempt to assign memory when outputSize is negative (or zero)

---

source/include/FluidMaxWrapper.hpp

It's. not clear that this is a greater than without this space (because it looks like the end of a nested template, or a bit shift, but not a template followed by a greater than, which is what it is).

Space required for clarity of code

---

jsui/fluid.plotter.js

This is something Rod found in the Max Beta and well it is certainly weird that it worked at all for so long... I think.
```js
function constructColorScheme() {
if (labelDict) {
const data = labelDict.get('data');
const keys = data.getkeys();
var uniques = new Array();
// How many unique labels are there?
keys.forEach(function(key) {
var label = data.get(key);
if (uniques.indexOf(label) == -1) {
uniques.push(label)
}
})
colorMap = {};
var scheme = strChunk(_colorscheme, 6);
uniques.sort();
uniques.forEach(function(u, i) {
i = i % scheme.length;
var color = hexToRGB(scheme[i], 1.0);
colorMap[u] = color;
});
// Strip any of the points from the pointColors if they have been assigned here
keys.forEach(function(pt) {
if (pointColors.hasOwnProperty(pt)) {
delete pointColors[pt]
}
}) …
```

fluid.plotter: correctly construct unique labels

---

source/include/clients/nrt/FluidListToBuf.hpp

#414 reproduces garbled error messages when `fluid.list2buf` is being hit from multiple threads. This fixes the garbled-ness, but we should think about whether the error in question could be improved. 
fixes #414

Fixes #414. Don't try and send `t_symbol` into `object_error`

---

source/include/FluidMaxWrapper.hpp

Unsuccessful `load` / `read`, e.g. with malformed JSON, would correctly be flagged as failures but the wrapper wasn't checking this status before just going ahead and wiping the old parameters. Resulting in crashing.

For `load` and `read` only update params on success :grimace:

---

source/include/FluidMaxWrapper.hpp

fixes #437 
`defer_low` is needed to properly deal with dialog boxes, it turns out, so `read, write` needed changing. The others are changed to minimize surprise, i.e. `(read, print)` should still work as expected, i.e. sequentially. `load / dump` maybe don't need to change, but I can imagine `(read, dump)` calls

Use `defer_low` for read, write, print, load, dump

---

source/include/FluidMaxWrapper.hpp
source/include/MaxBufferAdaptor.hpp

adjusts `#includes` of flucoma-core headers for the correspondingly named PR branch on core: https://github.com/flucoma/flucoma-core/pull/297

update flucoma core includes
